"""Json serialisation for user model added

Revision ID: 0411ab4b37c0
Revises: e81b1ec9cca1
Create Date: 2025-04-24 19:44:08.017814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0411ab4b37c0'
down_revision = 'e81b1ec9cca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_history',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ticketKey', sa.String(length=100), nullable=True),
    sa.Column('fromStatus', sa.String(length=100), nullable=True),
    sa.Column('toStatus', sa.String(length=100), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticketKey'], ['tickets.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_history')
    # ### end Alembic commands ###
