"""user model updated

Revision ID: 0f5b92004e58
Revises: 0411ab4b37c0
Create Date: 2025-04-24 21:26:46.497181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5b92004e58'
down_revision = '0411ab4b37c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_history',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ticketKey', sa.String(length=100), nullable=True),
    sa.Column('fromStatus', sa.String(length=100), nullable=True),
    sa.Column('toStatus', sa.String(length=100), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticketKey'], ['tickets.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    op.drop_table('ticket_history')
    # ### end Alembic commands ###
