"""project model amended to add last ticket number counter to the project

Revision ID: 1fcfb0712cd7
Revises: 0f5b92004e58
Create Date: 2025-04-25 23:20:46.761906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcfb0712cd7'
down_revision = '0f5b92004e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastTicketNumber', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('lastTicketNumber')

    # ### end Alembic commands ###
