"""Add Ticket Comment table to the models

Revision ID: 48c261c3a79b
Revises: 6f0fda4684f0
Create Date: 2025-05-07 10:02:06.833236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c261c3a79b'
down_revision = '6f0fda4684f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_comments',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ticketKey', sa.String(length=100), nullable=False),
    sa.Column('authorId', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticketKey'], ['tickets.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_comments')
    # ### end Alembic commands ###
