"""Add comment and field_changed to ticket_history

Revision ID: 6f0fda4684f0
Revises: 9dd14ea68948
Create Date: 2025-05-06 17:49:30.873848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0fda4684f0'
down_revision = '9dd14ea68948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('field_changed', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.drop_column('field_changed')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
