"""Ticket History model field name changed

Revision ID: e6d932c9ec72
Revises: 1fcfb0712cd7
Create Date: 2025-04-28 21:56:50.715448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6d932c9ec72'
down_revision = '1fcfb0712cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changedBy', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('ticket_history_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['changedBy'], ['id'])
        batch_op.drop_column('changed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changed_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ticket_history_ibfk_1', 'users', ['changed_by'], ['id'])
        batch_op.drop_column('changedBy')

    # ### end Alembic commands ###
