"""All models needed for phase 1 added

Revision ID: e81b1ec9cca1
Revises: 206a3849240f
Create Date: 2025-04-23 19:47:36.259117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81b1ec9cca1'
down_revision = '206a3849240f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_types',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('workflow_statuses',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('workflow_transitions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('fromStatus', sa.String(length=100), nullable=True),
    sa.Column('toStatus', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['fromStatus'], ['workflow_statuses.id'], ),
    sa.ForeignKeyConstraint(['toStatus'], ['workflow_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shortName', sa.String(length=10), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('shortName')
    )
    op.create_table('tickets',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('assignedTo', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('issueTypeId', sa.String(length=100), nullable=True),
    sa.Column('statusId', sa.String(length=100), nullable=True),
    sa.Column('projectId', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['assignedTo'], ['users.id'], ),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issueTypeId'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['statusId'], ['workflow_statuses.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ticket_history',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ticketKey', sa.Integer(), nullable=True),
    sa.Column('fromStatus', sa.String(length=100), nullable=True),
    sa.Column('toStatus', sa.String(length=100), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticketKey'], ['tickets.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_history')
    op.drop_table('tickets')
    op.drop_table('projects')
    op.drop_table('workflow_transitions')
    op.drop_table('workflow_statuses')
    op.drop_table('issue_types')
    # ### end Alembic commands ###
